name = "testing-rust-worker"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-27" # required

kv_namespaces = [
    { binding = "SOME_NAMESPACE", id = "", preview_id = "" },
    { binding = "FILE_SIZES", id = "", preview_id = "" },
]

vars = { SOME_VARIABLE = "some value" }

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }]

[[r2_buckets]]
binding = 'EMPTY_BUCKET'
bucket_name = ''
preview_bucket_name = 'empty_bucket'

[[r2_buckets]]
binding = 'PUT_BUCKET'
bucket_name = ''
preview_bucket_name = 'put_bucket'

[[r2_buckets]]
binding = 'SEEDED_BUCKET'
bucket_name = ''
preview_bucket_name = 'seeded_bucket'

[[r2_buckets]]
binding = 'DELETE_BUCKET'
bucket_name = ''
preview_bucket_name = 'delete_bucket'

[build]
command = "worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
